---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution_file_variety }}.yml'

- name: Add grafana YUM repositories.
  yum_repository:
    name: '{{ grafana_repo_name }}'
    description: '{{ grafana_repo_name }} YUM repository'
    file: '{{ grafana_repo_name }}'
    baseurl: '{{ grafana_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the grafana.
  yum:
    name: '{{ grafana_software }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_updated
  until: soft_updated is succeeded
  retries: 5
  delay: 2