{
 "title": "Azure Storage Account",
 "tags": [ "Insight" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_storageaccounts, subscription)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "label_values(azure_storageaccounts{subscription=\"$subscription\"}, resourcegroup)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(azure_storageaccounts{subscription=\"$subscription\",resourcegroup=\"$resourcegroup\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "singlestat",
   "description": "The percentage of availability for the storage service or the specified API operation. Availability is calculated by taking the TotalBillableRequests value and dividing it by the number of applicable requests, including those that produced unexpected errors. All unexpected errors result in reduced availability for the storage service or the specified API operation.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"Availability\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"Egress\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Network Out"
    },
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"Ingress\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Network In"
    }
   ]
  },
  {
   "title": "UsedCapacity",
   "type": "singlestat",
   "description": "The amount of storage used by the storage account. For standard storage accounts, it's the sum of capacity used by blob, table, file, and queue. For premium storage accounts and Blob storage accounts, it is the same as BlobCapacity or FileCapacity.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"UsedCapacity\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "UsedCapacity",
   "type": "graph",
   "description": "The amount of storage used by the storage account. For standard storage accounts, it's the sum of capacity used by blob, table, file, and queue. For premium storage accounts and Blob storage accounts, it is the same as BlobCapacity or FileCapacity.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"UsedCapacity\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "SuccessE2ELatency: The average end-to-end latency of successful requests made to a storage service or the specified API operation.\n\nSuccessServerLatency: The average time used to process a successful request by Azure Storage. This value does not include the network latency specified in SuccessE2ELatency.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"SuccessE2ELatency\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " Success E2E Latency"
    },
    {
     "expr": "azure_storageaccounts{aggregation=\"average\",metric=\"SuccessServerLatency\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Success Server Latency"
    }
   ]
  }
 ]
}