{
 "title": "Azure Cache for Redis",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_redis, subscription)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "label_values(azure_redis{subscription=\"$subscription\"}, resourcegroup)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(azure_redis{subscription=\"$subscription\",resourcegroup=\"$resourcegroup\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Miss Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cachemissrate\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemorypercentage\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per Second" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"operationsPerSecond\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Saturation and Server Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"percentProcessorTime\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"serverLoad\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Server Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemory\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemoryRss\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Rss"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"evictedkeys\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Evicted"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"expiredkeys\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"totalkeys\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"getcommands\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Gets"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"setcommands\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Sets"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"connectedclients\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cacheRead\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cacheWrite\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}