{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(kafka_brokers, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(kafka_brokers{customer=~\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(kafka_brokers{customer=~\"$customer\",environment=~\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(kafka_brokers{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\"},group)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_brokers{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\",group=~\"$group\"},cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_brokers{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{cluster=\"$cluster\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (topic) (kafka_topic_partitions{cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{cluster=\"$cluster\"}) / avg(kafka_brokers{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{cluster='$cluster'}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster=\"$cluster\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{cluster=\"$cluster\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster='$cluster'}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}