{
 "title": "Logstash Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(logstash_exporter_build_info, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(logstash_exporter_build_info{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(logstash_exporter_build_info{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(logstash_exporter_build_info{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(logstash_node_mem_heap_max_bytes{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(logstash_node_mem_heap_max_bytes{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "logstash_info_node{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}"
    },
    {
     "expr": "avg by (instance)(logstash_node_mem_heap_max_bytes{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "PIPELINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_duration_seconds_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events in rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_in_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events filtered rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_filtered_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events out rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_out_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "PLUGINS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_duration_seconds_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Failures rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_failures_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events In rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_in_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events Out rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_mem_heap_used_bytes{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} - heap used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_process_open_filedescriptors{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "s", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_duration_seconds_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  }
 ]
}