{
 "title": "Minio Overview",
 "description": "minio dashboard",
 "tags": [
  "object-storage",
  "Insight"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(minio_disks_offline, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(minio_disks_offline{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(minio_disks_offline{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(minio_disks_offline{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(minio_disks_offline{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"}, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(disk_storage_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(bucket_usage_size{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Data Growth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(bucket_usage_size{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, sum(bucket_objects_count{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"}))"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum by (object_size) (bucket_objects_histogram{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})",
     "legendFormat": "{{object_size}}"
    }
   ]
  },
  {
   "title": "Total disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disks_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (process_open_fds{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Offline disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disks_offline{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (go_goroutines{service=\"minio\",customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "In/Out Throughput of S3",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_rx_bytes_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(s3_tx_bytes_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Transmited"
    }
   ]
  },
  {
   "title": "In/Out Throughput of Internode",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(internode_rx_bytes_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(internode_tx_bytes_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Transmited"
    }
   ]
  }
 ]
}