{
 "title": "Netdata Overview",
 "description": "Netdata dashboards for Grafana via Prometheus.",
 "tags": [ "Insight" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(netdata_info, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(netdata_info{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(netdata_info{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(netdata_info{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
   },
   {
    "name": "instance",
    "label": "Host",
    "query": "label_values(netdata_info{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},instance)"
   },
   {
    "name": "view",
    "label": "View",
    "query": "metrics(netdata_.+_cpu_cpu_time___average)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(netdata_system_uptime_seconds_average, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "VCores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(netdata_cpu_cpu_percentage_average{instance=\"$instance\",dimension=\"idle\"})"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_swap_MiB_average{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GiB_average{instance=\"$instance\"})"
    }
   ]
  },
  { "title": "System overview: CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU utilization",
   "type": "graph",
   "description": "Total CPU utilization (all cores). 100% here means there is no CPU idle time at all. You can get per core usage at the _CPUs_ section and per application usage at the _Applications monitoring_ section.\n\nKeep an eye on **iowait**. If it is constantly high, your disks are a bottleneck and they slow your system down.\n\nAn important metric worth monitoring, is **softirq**. A constantly high percentage of softirq may indicate network driver issues.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average{dimension!~\"idle\",instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Service CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,irate(netdata_users_cpu_percentage_average{instance=\"$instance\"}[10m]))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  { "title": "System overview: RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "description": "System Random Access Memory (i.e. physical memory) usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{dimension!=\"free\",instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_system_ram_MiB_average{dimension=\"free\",instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Service Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,(netdata_users_mem_MiB_average{instance=\"$instance\"}))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "System overview: load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "System load average",
     "type": "graph",
     "description": "Current system load, i.e. the number of processes using CPU or waiting for system resources (usually CPU and disk). The 3 metrics refer to 1, 5 and 15 minute averages. The system calculates this once every 5 seconds.\n\nFor more information check this [Wikipedia article](https://en.wikipedia.org/wiki/Load_(computing))",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "netdata_system_load_load_average{dimension!=\"load15\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_system_load_load_average{dimension=\"load15\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "graph",
     "description": "Total Disk I/O, for all physical disks. You can get detailed information about each disk at the _Disks_ section and per application Disk usage at the _Applications Monitoring_ section.\n\nPhysical are all the disks that are listed in `/sys/block`, but do not exist in `/sys/devices/virtual/block`.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_io_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Memory paged from/to disk",
     "type": "graph",
     "description": "Memory paged from/to disk. This is usually the total disk I/O of the system.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_pgpgio_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "System swap",
     "type": "graph",
     "description": "System swap memory usage. Swap space is used when the amount of physical memory (RAM) is full. When the system needs more memory resources and the RAM is full, inactive pages in memory are moved to the swap space (usually a disk, a disk partition or a file).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_swap_MiB_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Swap I/O",
     "type": "graph",
     "description": "Total Swap I/O. (netdata measures both `in` and `out`. If either of them is not shown in the chart, it is because it is zero - you can change the page settings to always render all the available dimensions on all charts).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_swapio_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network bandwidth",
     "type": "graph",
     "description": "Total IPv4 Traffic.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_net_kilobits_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "System processes",
     "type": "graph",
     "description": "System processes. **Running** are the processes in the CPU. **Blocked** are processes that are willing to enter the CPU, but they cannot, e.g. because they wait for disk activity.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "processes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_processes_processes_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Started processes",
     "type": "graph",
     "description": "Number of new processes created.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "processes/s" }
     ],
     "targets": [
      {
       "expr": "netdata_system_forks_processes_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "System active processes",
     "type": "graph",
     "description": "All system processes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "processes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_active_processes_processes_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU context switches",
     "type": "graph",
     "description": "[Context Switches](https://en.wikipedia.org/wiki/Context_switch), is the switching of the CPU from one process, task or thread to another. If there are many processes or threads willing to execute and very few CPU cores available to handle them, the system is making more context switching to balance the CPU resources among them. The whole process is computationally intensive. The more the context switches, the slower the system gets.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "context switches/s" }
     ],
     "targets": [
      {
       "expr": "netdata_system_ctxt_context_switches_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: idle jitter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU idle jitter",
     "type": "graph",
     "description": "Idle jitter is calculated by netdata. A thread is spawned that requests to sleep for a few microseconds. When the system wakes it up, it measures how many microseconds have passed. The difference between the requested and the actual duration of the sleep, is the idle jitter. This number is useful in real-time environments, where CPU jitter can affect the quality of the service (like VoIP media gateways).",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_idlejitter_microseconds_lost_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU interrupts",
     "type": "graph",
     "description": "Total number of CPU interrupts. Check the system interrupts graph that gives more detail about each interrupt and also the _CPUs_ section where interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "interrupts/s" }
     ],
     "targets": [
      {
       "expr": "netdata_system_intr_interrupts_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "System interrupts",
     "type": "graph",
     "description": "CPU interrupts in detail. At the _CPUs_ section, interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "interrupts/s" }
     ],
     "targets": [
      {
       "expr": "netdata_system_interrupts_interrupts_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: softirqs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "System softirqs",
     "type": "graph",
     "description": "CPU softirqs in detail. At the _CPUs_ section, softirqs are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "softirqs/s" }
     ],
     "targets": [
      {
       "expr": "netdata_system_softirqs_softirqs_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  }
 ]
}