{
 "title": "Prometheus Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(prometheus_api_remote_read_queries, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(prometheus_api_remote_read_queries{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(prometheus_api_remote_read_queries{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(prometheus_api_remote_read_queries{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(prometheus_api_remote_read_queries{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAL Fsync Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{instance=\"$host\"}[3h])/rate(prometheus_tsdb_wal_fsync_duration_seconds_count{instance=\"$host\"}[3h])"
    }
   ]
  },
  {
   "title": "Head GC Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{instance=\"$host\"}[3h])/rate(prometheus_tsdb_head_gc_duration_seconds_count{instance=\"$host\"}[3h])"
    }
   ]
  },
  {
   "title": "Scrapes Performed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Samples Ingested",
   "type": "singlestat",
   "description": "Samples Ingested per second through scraping activity",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$host\"}[$interval]) or irate(prometheus_tsdb_head_samples_appended_total{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Active Data blocks",
   "type": "singlestat",
   "description": "Number of currently loaded data blocks",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Active Series",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{instance=\"$host\"}",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Head Block Retention",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time{instance=\"$host\"} - prometheus_tsdb_head_min_time{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Avg Compaction Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{instance=\"$host\",service=\"prometheus\"}[6h])/rate(prometheus_tsdb_compaction_duration_seconds_count{instance=\"$host\",service=\"prometheus\"}[3h])"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Prometheus Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$host\",service=\"prometheus\"}[$interval]) or irate(process_cpu_seconds_total{instance=\"$host\",service=\"prometheus\"}[5m])",
     "legendFormat": "CPU Cores Used"
    },
    {
     "expr": "count(node_cpu{mode=\"user\", instance=\"$host\",service=\"prometheus\"})",
     "legendFormat": "CPU Cores Total"
    },
    {
     "expr": "count(node_cpu{mode=\"user\", instance=\"$host\",service=\"prometheus\"})*0.75",
     "legendFormat": "Recommended Limit"
    }
   ]
  },
  {
   "title": "Prometheus Process  Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$host\",service=\"prometheus\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"$host\",service=\"prometheus\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$host\",service=\"prometheus\"}+go_memstats_stack_inuse_bytes{instance=\"$host\",service=\"prometheus\"}",
     "legendFormat": "Go Memory Allocated and In Use"
    },
    {
     "expr": "node_memory_MemTotal{instance=\"$host\",service=\"prometheus\"}",
     "legendFormat": "Total System Memory"
    }
   ]
  },
  {
   "title": "Head Block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(prometheus_tsdb_head_chunks{instance=\"$host\"}[$interval]) ",
     "legendFormat": "Chunks"
    },
    {
     "expr": "max_over_time(prometheus_tsdb_head_series{instance=\"$host\"}[$interval]) ",
     "legendFormat": "Series "
    },
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{instance=\"$host\"}[6h])/rate(prometheus_tsdb_compaction_chunk_size_count{instance=\"$host\"}[6h])*(max_over_time(prometheus_tsdb_head_chunks{instance=\"$host\"}[$interval]) )",
     "legendFormat": "Size (Estimated)"
    }
   ]
  },
  {
   "title": "Active Data Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(prometheus_tsdb_blocks_loaded{instance=\"$host\"}[$interval])",
     "legendFormat": "Active (Loaded) Data Blocks"
    }
   ]
  },
  { "title": "Storage (TSDB) Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Chunk Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{instance=\"$host\"}[$interval]) or irate(prometheus_tsdb_head_chunks_created_total{instance=\"$host\"}[5m])",
     "legendFormat": "Chunks Created"
    },
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{instance=\"$host\"}[$interval]) or irate(prometheus_tsdb_head_chunks_removed_total{instance=\"$host\"}[5m])",
     "legendFormat": "Chunks Removed"
    }
   ]
  },
  {
   "title": "Reload block data from disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(prometheus_tsdb_reloads_total{instance=\"$host\"}[$interval]) - rate(prometheus_tsdb_reloads_failures_total{instance=\"$host\"}[$interval])) or (irate(prometheus_tsdb_reloads_total{instance=\"$host\"}[5m]) - irate(prometheus_tsdb_reloads_failures_total{instance=\"$host\"}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{instance=\"$host\"}[$interval]) or irate(prometheus_tsdb_reloads_failures_total{instance=\"$host\"}[5m])",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ingestion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[5m]))",
     "legendFormat": "Scrapes Performed"
    },
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$host\"}[$interval]) or irate(prometheus_tsdb_head_samples_appended_total{instance=\"$host\"}[5m])",
     "legendFormat": "Samples appended in the head block"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up)", "legendFormat": "Targets Configured" },
    {
     "expr": "sum(avg_over_time(up{instance=\"$host\"}[$interval])) or  sum(avg_over_time(up{instance=\"$host\"}[5m]))",
     "legendFormat": "Avg Succesfully Scraped Targets"
    },
    {
     "expr": "sum(min_over_time(up{instance=\"$host\"}[$interval])) or  sum(min_over_time(up{instance=\"$host\"}[5m]))",
     "legendFormat": "Min Successfully Scraped Targets"
    }
   ]
  },
  {
   "title": "Scraped Target by Job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(up{instance=\"$host\"}[$interval])) by (job) or sum(avg_over_time(up{instance=\"$host\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Time by Job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(scrape_duration_seconds{instance=\"$host\"}[$interval])) by (job) or avg(avg_over_time(scrape_duration_seconds{instance=\"$host\"}[5m])) by (job) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scraped Target by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(up{instance=\"$host\"}[$interval])) by (instance) or sum(avg_over_time(up{instance=\"$host\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Time by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(scrape_duration_seconds{instance=\"$host\"}[$interval])) by (instance) or avg(avg_over_time(scrape_duration_seconds{instance=\"$host\"}[5m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrapes by Target Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[$interval]) or irate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[5m])",
     "legendFormat": "Rate of {{interval}} scrapes"
    }
   ]
  },
  {
   "title": "Scrape Frequency Versus Target",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(prometheus_target_interval_length_seconds_sum{instance=\"$host\"}[$interval]) / rate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[$interval])) or (irate(prometheus_target_interval_length_seconds_sum{instance=\"$host\"}[5m]) / irate(prometheus_target_interval_length_seconds_count{instance=\"$host\"}[5m]))",
     "legendFormat": "Actual  {{interval}} scrape interval  length"
    }
   ]
  },
  {
   "title": "Scraping Time Drift",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - node_time{instance=\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Interval Variance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"1s\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"1s\",quantile=\"0.01\"}) by ())/1",
     "legendFormat": "1sec  Target Interval Variance"
    },
    {
     "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"5s\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"5s\",quantile=\"0.01\"}) by ())/5",
     "legendFormat": "5sec Target Interval Variance"
    },
    {
     "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"1m0s\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"$host\",interval=\"1m0s\",quantile=\"0.01\"}) by ())/60",
     "legendFormat": "1min Target Interval Variance"
    }
   ]
  },
  {
   "title": "Slowest Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,max_over_time(scrape_duration_seconds{instance=\"$host\"}[$interval]) or max_over_time(scrape_duration_seconds{instance=\"$host\"}[5m]))",
     "legendFormat": "{{job}} at {{service}}"
    }
   ]
  },
  {
   "title": "Largest Samples Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max_over_time(scrape_samples_scraped{instance=\"$host\"}[$interval]) or max_over_time(scrape_duration_seconds{instance=\"$host\"}[5m]))",
     "legendFormat": "{{job}} at {{service}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Prometheus Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(prometheus_engine_queries{instance=\"$host\"}[$interval]) or avg_over_time(prometheus_engine_queries{instance=\"$host\"}[5m])",
     "legendFormat": "Avg Queries Active"
    },
    {
     "expr": "max_over_time(prometheus_engine_queries{instance=\"$host\"}[$interval]) or max_over_time(prometheus_engine_queries{instance=\"$host\"}[5m])",
     "legendFormat": "Max Queries Active"
    },
    {
     "expr": "prometheus_engine_queries_concurrent_max{instance=\"$host\"}",
     "legendFormat": "Maximum Queries Permitted"
    }
   ]
  },
  {
   "title": "Prometheus Query Execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{instance=\"$host\"}[$interval]) or irate(prometheus_engine_query_duration_seconds_count{instance=\"$host\"}[$interval]) ",
     "legendFormat": "{{slice}} - Executed"
    }
   ]
  },
  {
   "title": "Prometheus Query Execution Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(prometheus_engine_query_duration_seconds_sum{instance=\"$host\"}[$interval])/rate(prometheus_engine_query_duration_seconds_count{instance=\"$host\"}[$interval])) or (irate(prometheus_engine_query_duration_seconds_sum{instance=\"$host\"}[$interval])/irate(prometheus_engine_query_duration_seconds_count{instance=\"$host\"}[$interval]))",
     "legendFormat": "{{slice}} - Avg Time"
    }
   ]
  },
  {
   "title": "Prometheus Query Execution Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{instance=\"$host\"}[$interval])",
     "legendFormat": "{{slice}} - Load"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "HTTP Requests duration by Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[$interval]) or irate(prometheus_http_request_duration_seconds_sum[$interval])\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Response Average Size by Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_response_size_bytes_sum[$interval]) or\nirate(prometheus_http_response_size_bytes_sum[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Time Series Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Top 10 metrics by time series count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Top 10 hosts by time series count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "topk(10, count({__name__=~\".+\"}) by (instance))"
    }
   ]
  }
 ]
}