{
 "title": "Trickster Overview",
 "description": "Dashboard for Trickster delta cache for Prometheus and other TSDB",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "group",
    "label": "Group",
    "query": "trickster_cache_max_usage_bytes"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "trickster_cache_max_usage_bytes{group=\"$group\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Cache",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "trickster_cache_max_usage_bytes{instance=\"$host\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Prometheus Query elapsed time",
   "type": "graph",
   "description": "This shows how long did it take  Prometheus to server requests.\nThis could be possibly lower time when using Trickster since the queries can be for smaller more recent time range.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_engine_query_duration_seconds{instance=\"$host\"}) by (slice)",
     "legendFormat": "{{ slice }}"
    }
   ]
  },
  {
   "title": "Prometheus Request count",
   "type": "graph",
   "description": "Shows total request count on Prometheus server.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=\"$host\"}[5m])) by (handler) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration per handler",
   "type": "graph",
   "description": "Shows duration how long it takes to Prometheus to server requests aggregated by handlers",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_microseconds{instance=\"$host\"}) by (handler, quantile)",
     "legendFormat": "{{ handler }} {{ quantile }}"
    }
   ]
  },
  {
   "title": "Cache hit",
   "type": "singlestat",
   "description": "Shows percentage of query cache hit of Trickster. ",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(trickster_proxy_points_total{cache_status=\"cached\",instance=\"$host\"}) / sum(trickster_proxy_points_total{instance=\"$host\"})"
    }
   ]
  }
 ]
}