{
 "title": "WebSite Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(probe_dns_lookup_time_seconds,customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\"},environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\"},project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\",project=\"$project\"},group)"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},target)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status code",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_http_status_code{target=\"$target\"})"
    }
   ]
  },
  {
   "title": "Request by phase",
   "type": "graph",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg by (phase) (probe_http_duration_seconds{target=\"$target\"}) * 1000",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL cert expiry",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((probe_ssl_earliest_cert_expiry{target=\"$target\"}-time()) / 86400)"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_ip_protocol{target=\"$target\"})"
    }
   ]
  },
  {
   "title": "Version of SSL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "avg by (version) (probe_tls_version_info{target=\"$target\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}