{
 "title": "Cross Server Graphs",
 "tags": [ "OS" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(os_info, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(os_info{customer=~\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(os_info{customer=~\"$customer\",environment=~\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(os_info{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\"},group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(os_info{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\",group=~\"$group\"},instance)"
   },
   {
    "name": "interface",
    "query": "label_values(os_info{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\",group=~\"$group\",instance=~\"$host\"},interface)"
   }
  ]
 },
 "panels": [
  {
   "title": "Specifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "os_info{instance=~\"$host\"}"
    },
    {
     "expr": "sum by(instance)(windows_cs_logical_processors{instance=~\"$host\"}) or count by(instance)(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"})"
    },
    {
     "expr": "(sum by(instance)(node_memory_MemTotal_bytes{instance=~\"$host\"}) or sum by(instance)(windows_os_visible_memory_bytes{instance=~\"$host\"}))"
    },
    {
     "expr": "sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) + sum by(instance)(node_memory_SwapTotal_bytes{instance=~\"$host\"}) or sum by(instance)(windows_logical_disk_size_bytes{instance=~\"$host\"})"
    },
    {
     "expr": "(time() - windows_system_system_up_time{instance=~\"$host\"}) or ((time() - node_boot_time_seconds{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Combine CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m]))) * 100 or (1 - avg(irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"}) * 100 or avg((windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"}) / windows_cs_physical_memory_bytes{instance=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "(1- sum(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum (node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) * 100 or (1- sum(windows_logical_disk_free_bytes{instance=~\"$host\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$host\"})) * 100"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(count(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (count(windows_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0))",
     "legendFormat": "Instance"
    },
    {
     "expr": "(sum(windows_cs_logical_processors{instance=~\"$host\"}) or vector(0)) + (count(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"}) or vector(0))",
     "legendFormat": "Processor"
    },
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (sum(windows_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0))) / 1024 / 1024 / 1005",
     "legendFormat": "Memory in Gigabytes"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) or vector(0)) + (sum(node_memory_SwapTotal_bytes{instance=~\"$host\"}) or vector(0)) + (sum(windows_logical_disk_size_bytes{instance=~\"$host\"}) or vector(0))) / 1024 / 1024 / 1023.5",
     "legendFormat": "Storage in Gigabytes"
    }
   ]
  },
  {
   "title": "Combine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(100 - avg by(instance)(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m])) * 100) or (100 - avg by(instance)(irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"}) * 100 or ((windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"}) / windows_cs_physical_memory_bytes{instance=~\"$host\"}) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "graph",
   "description": "Percentage of usage disk space on mount for Linux.\nPercentage of usage disk space exclude reserve partition for Windows.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(1- sum by(instance)(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) * 100 or (1- sum by(instance)(windows_logical_disk_free_bytes{instance=~\"$host\"}) / sum by(instance)(windows_logical_disk_size_bytes{instance=~\"$host\"})) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "WMI calculate total traffic because don't know how to calculate variables array of multiple network interfaces.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=~\"$host\", device=~\"$interface\"}[5m]) + irate(node_network_transmit_bytes_total{instance=~\"$host\", device=~\"$interface\"}[5m])) by (instance)) or (sum(irate(windows_net_bytes_sent_total{instance=~\"$host\"}[5m]) + irate(windows_net_bytes_received_total{instance=~\"$host\"}[5m])) by (instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}