{
 "title": "Windows System Overview",
 "description": "Windows System Overview",
 "tags": [
  "OS",
  "Windows"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(windows_system_system_up_time, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(windows_system_system_up_time{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(windows_system_system_up_time{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(windows_system_system_up_time{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(windows_system_system_up_time{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "os_info{instance=\"$host\"}",
     "legendFormat": "{{ build }}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "os_info{instance=\"$host\"}",
     "legendFormat": "{{ vmsize }}"
    }
   ]
  },
  {
   "title": "VCores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "description": "Memory + SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Sum of disk space on all partitions.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_logical_disk_size_bytes{instance=\"$host\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg by(instance)(irate(windows_cpu_time_total{mode=\"idle\", instance=\"$host\"}[5m]))) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{instance=\"$host\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$host\"}",
     "legendFormat": "Physical memory"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=\"$host\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=\"$host\"} - windows_os_physical_memory_free_bytes{instance=\"$host\"}) / windows_cs_physical_memory_bytes{instance=\"$host\"} * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "System Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{instance=\"$host\"}",
     "legendFormat": "system threads"
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(windows_service_state{instance=\"$host\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network discarded/error packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(windows_net_packets_outbound_discarded{instance=\"$host\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{instance=\"$host\"}[5m])",
       "legendFormat": "Sent {{nic}}"
      },
      {
       "expr": "irate(windows_net_packets_received_discarded{instance=\"$host\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{instance=\"$host\"}[5m])",
       "legendFormat": "Received {{nic}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(windows_net_bytes_sent_total{instance=\"$host\"}[5m]) >0",
       "legendFormat": "Sent {{nic}}"
      },
      {
       "expr": "- rate(windows_net_bytes_received_total{instance=\"$host\"}[5m]) <0",
       "legendFormat": "Received {{nic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hard Disk Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(windows_logical_disk_write_bytes_total{instance=\"$host\", volume !~\"HarddiskVolume.+\"}[5m])",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "- irate(windows_logical_disk_read_bytes_total{instance=\"$host\", volume !~\"HarddiskVolume.+\"}[5m])",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Hard Disk I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(windows_logical_disk_split_ios_total{instance=\"$host\", volume !~\"HarddiskVolume.+\"}[5m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Hard Disk Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "windows_logical_disk_free_bytes{instance=\"$host\", volume !~\"HarddiskVolume.+\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Hard Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - windows_logical_disk_free_bytes{instance=\"$host\", volume !~\"HarddiskVolume.+\"} / windows_logical_disk_size_bytes{instance=\"$host\", volume !~\"HarddiskVolume.+\"}) * 100",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  }
 ]
}