{
 "title": "Azure SQL Managed Instance",
 "tags": [ "Databases" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_sqlmanagedinstance, subscription)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "label_values(azure_sqlmanagedinstance{subscription=\"$subscription\"}, resourcegroup)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(azure_sqlmanagedinstance{subscription=\"$subscription\",resourcegroup=\"$resourcegroup\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"avg_cpu_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "vCores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"virtual_core_count\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"reserved_storage_mb\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"io_bytes_read\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " Read"
    },
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"io_bytes_written\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"io_requests\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"storage_space_used_mb\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "azure_sqlmanagedinstance{aggregation=\"average\",metric=\"reserved_storage_mb\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}