{
 "title": "Azure Database for PostgreSQL",
 "tags": [ "Databases" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_pgsql, subscription)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "label_values(azure_pgsql{subscription=\"$subscription\"}, resourcegroup)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(azure_pgsql{subscription=\"$subscription\",resourcegroup=\"$resourcegroup\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"storage_limit\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Storage limit"
    },
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"storage_used\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "Serverlog Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"serverlog_storage_limit\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Storage limit"
    },
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"serverlog_storage_usage\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"active_connections\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"pg_replica_log_delay_in_seconds\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"} or vector(0)"
    }
   ]
  },
  {
   "title": "Operating load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"cpu_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "CPU utilization"
    },
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"io_consumption_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"memory_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"storage_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"serverlog_storage_percent\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"}",
     "legendFormat": "Log"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"network_bytes_ingress\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"} or vector(0)",
     "legendFormat": "Network In"
    },
    {
     "expr": "azure_pgsql{aggregation=\"average\",metric=\"network_bytes_egress\",subscription=\"$subscription\",resourcegroup=\"$resourcegroup\",host=\"$host\"} or vector(0)",
     "legendFormat": "Network Out"
    }
   ]
  }
 ]
}