{
 "title": "MySQL InnoDB Compression",
 "tags": [ "Databases" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(mysql_up, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(mysql_up{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(mysql_up{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(mysql_up{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"}, instance)"
   },
   {
    "name": "buffer",
    "query": "label_values(mysql_info_schema_innodb_cmpmem_pages_used_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",instance=\"$host\"},buffer_pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistic of compression operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Compress Attempts",
   "type": "graph",
   "description": "Number of compression operations attempted. Pages are compressed whenever an empty page is created or the space for the uncompressed modification log runs out.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_cmp_compress_ops_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_cmp_compress_ops_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  {
   "title": "Uncompressed Attempts",
   "type": "graph",
   "description": "Number of uncompression operations performed. Compressed InnoDB pages are uncompressed whenever compression fails, or the first time a compressed page is accessed in the buffer pool and the uncompressed page does not exist.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_cmp_uncompress_ops_total{instance=\"$host\"}[$interval]) or \nirate(mysql_info_schema_innodb_cmp_uncompress_ops_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  {
   "title": "Compression Success Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{instance=\"$host\"}[$interval])/\nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{instance=\"$host\"}[$interval]) or \nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{instance=\"$host\"}[5m])/\nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  { "title": "CPU Core Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Core Usage for Compression",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(mysql_info_schema_innodb_cmp_compress_time_seconds_total{instance=\"$host\"}[$interval])) by (instance) or\nsum(irate(mysql_info_schema_innodb_cmp_compress_time_seconds_total{instance=\"$host\"}[5m])) by (instance)) /\ncount(node_cpu_seconds_total{mode=\"user\", instance=\"$host\"}) by (instance) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Core Usage for Uncompression",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(mysql_info_schema_innodb_cmp_uncompress_time_seconds_total{instance=\"$host\"}[$interval])) by (instance) or\nsum(irate(mysql_info_schema_innodb_cmp_uncompress_time_seconds_total{instance=\"$host\"}[5m])) by (instance)) /\ncount(node_cpu_seconds_total{mode=\"user\", instance=\"$host\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Buffer Pool Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Used Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(page_size) (mysql_info_schema_innodb_cmpmem_pages_used_total{instance=\"$host\"})",
     "legendFormat": "{{page_size}}"
    }
   ]
  },
  {
   "title": "Total Free Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(page_size) (mysql_info_schema_innodb_cmpmem_pages_free_total{instance=\"$host\"})",
     "legendFormat": "{{page_size}}"
    }
   ]
  },
  { "title": "Buffer Pool  $buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "buffer" },
  {
   "title": "Used Pages (Buffer Pull $buffer)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_cmpmem_pages_used_total{instance=\"$host\",buffer_pool=~\"$buffer\"}",
     "legendFormat": "{{page_size}}"
    }
   ]
  },
  {
   "title": "Pages Free (Buffer Pull $buffer)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_cmpmem_pages_free_total{instance=\"$host\",buffer_pool=\"$buffer\"}",
     "legendFormat": "{{page_size}}"
    }
   ]
  }
 ]
}